### ISSUE TITLE
Gold standard is updated

### ISSUE THREAD

**Issue by yusukefukuju** [sisap-challenges/sisap23-laion-challenge-evaluation#2]
Dear @maumueller @sadit ,

I noticed an update to the gold standard dataset on the competition's [news page](https://sisap-challenges.github.io/#fndef:1) and I was wondering how it pertains to the competition evaluation.

Should we replace the existing [ground truth dataset URL](https://github.com/sisap-challenges/sisap23-laion-challenge-evaluation/blob/master/eval.py#L16) in this library with the updated one? Or do you know if the update is not relevant to the evaluation for this competition?

Thank you for your time and support.

Best,
@kondounagi

**Comment by sadit** [comment]
Dear @kondounagi 

The impact is negligible if you replace the old ground truth with the new one; that is the short answer.

The large answer is that some distances were negative, and some differences were found by Vladimir Mic while checking the distance values consistency. He informed us, and we recomputed it with high-precision floating point arithmetic. The net effect was small; the overall recall statistics should remain.

However, there is another complex issue, also found by Vladimir, induced by the high number of near-duplicated elements in the database for some query objects (there is even a recent paper about this issue in LAION...). This is an issue of the database and, therefore, is hard to overcome. We seek the best strategy to solve the bad effects in the public query set (what you are using) without changing too many things or the evaluation metric. The private query set will be free of this problem anyway, so the final rank should not be affected.

Best regards,
Eric

**Comment by yusukefukuju** [comment]
@sadit Thank you for your kind and quick response!
I'll do my best in this competition !
